config/routes.rb
Rails.application.routes.draw do
  resources :networths
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/networth.rb
class Networth < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/networths_controller.rb
class NetworthsController < ApplicationController
  before_action :set_networth, only: [:show, :edit, :update, :destroy]

  # GET /networths
  # GET /networths.json
  def index
    @networths = Networth.all
  end

  # GET /networths/1
  # GET /networths/1.json
  def show
  end

  # GET /networths/new
  def new
    @networth = Networth.new
  end

  # GET /networths/1/edit
  def edit
  end

  # POST /networths
  # POST /networths.json
  def create
    @networth = Networth.new(networth_params)

    respond_to do |format|
      if @networth.save
        format.html { redirect_to @networth, notice: 'Networth was successfully created.' }
        format.json { render :show, status: :created, location: @networth }
      else
        format.html { render :new }
        format.json { render json: @networth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /networths/1
  # PATCH/PUT /networths/1.json
  def update
    respond_to do |format|
      if @networth.update(networth_params)
        format.html { redirect_to @networth, notice: 'Networth was successfully updated.' }
        format.json { render :show, status: :ok, location: @networth }
      else
        format.html { render :edit }
        format.json { render json: @networth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /networths/1
  # DELETE /networths/1.json
  def destroy
    @networth.destroy
    respond_to do |format|
      format.html { redirect_to networths_url, notice: 'Networth was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_networth
      @networth = Networth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def networth_params
      params.require(:networth).permit(:value, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/networths_helper.rb
module NetworthsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trackato</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/networths/_form.html.erb
<%= form_with(model: networth, local: true) do |form| %>
  <% if networth.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(networth.errors.count, "error") %> prohibited this networth from being saved:</h2>

      <ul>
      <% networth.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/networths/edit.html.erb
<h1>Editing Networth</h1>

<%= render 'form', networth: @networth %>

<%= link_to 'Show', @networth %> |
<%= link_to 'Back', networths_path %>

app/views/networths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Networths</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @networths.each do |networth| %>
      <tr>
        <td><%= networth.value %></td>
        <td><%= networth.date %></td>
        <td><%= link_to 'Show', networth %></td>
        <td><%= link_to 'Edit', edit_networth_path(networth) %></td>
        <td><%= link_to 'Destroy', networth, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Networth', new_networth_path %>


<%= line_chart Networth.pluck(:date, :value) %>

app/views/networths/new.html.erb
<h1>New Networth</h1>

<%= render 'form', networth: @networth %>

<%= link_to 'Back', networths_path %>

app/views/networths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @networth.value %>
</p>

<p>
  <strong>Date:</strong>
  <%= @networth.date %>
</p>

<%= link_to 'Edit', edit_networth_path(@networth) %> |
<%= link_to 'Back', networths_path %>